---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Homepage
- type: document
  path: content/_index.md
  label: Homepage
- type: document
  path: content/about.md
  label: About
- type: directory
  path: content/theme
  label: All Themes
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - post
- type: heading
  label: All Pages
- type: directory
  path: content
  label: All Pages
  create: all
  match: "**/*"
  exclude: _index.md
- type: heading
  label: Configuration
- type: document
  path: config.toml
  label: Configuration
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.90.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.90.0